export const siteConfig = {
  site: "https://mohammedsh.xyz",
  title: "Mohx Notes",
  description:
    "A corner of the internet where I write, build, and share my story through code, design, and quiet thoughts.",
  og: "/avatar.svg",
  favicon: "/favicon.svg",
  author: "Mohammed",

  navLinks: [
    { label: "Root", href: "/" },
    { label: "Blog", href: "/blog" },
    { label: "Projects", href: "/projects" },
    { label: "About", href: "/about" },
    { label: "Donate", href: "/donate" },
    // { label: "Guestbook", href: "/guestbook" },
  ],

  contacts: [
    { icon: "mail", text: "hello@mohammedsh.com", href: "mailto:hello@mohammedsh.xyz" },
    { icon: "send", text: "@mohxmdsh", href: "https://t.me/mohxmdsh" },
    {
      icon: "at-sign",
      text: "@mohxmd@mstdn.social",
      href: "https://mstdn.social/@mhdZhHan",
    },
    { icon: "github", text: "@mohxmd", href: "https://github.com/mohxmd" },
    {
      icon: "linkedin",
      text: "/in/mohammedshajahan",
      href: "https://linkedin.com/in/mohammedshajahan",
    },
    {
      icon: "instagram",
      text: "@mohxmd__",
      href: "https://instagram.com/mohxmd__",
    },
    { icon: "arcticons:x-twitter", text: "@mohxmdsh", href: "https://x.com/mohxmdsh" },
  ],

  keywords: [
    "mohx notes",
    "MohxNotes",
    "mohammed's blog",
    "mohammedsh",
    "mohammed shajahan",
    "hello world",
    "mhdzhhan",
    "mohxmd",
    "mohxmdsh",
    "mohxmd__",
    "mohx",
    "programming",
    "linux",
    "kde",
    "anime",
    "manga",
    "islam",
    "tech",
    "tips",
    "tutorials",
    "development",
    "web development",
    "app development",
    "ai",
    "ml",
  ],
};
